backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true # run npx netlify-cms-proxy-server for local testing

# media_folder_relative: true
media_folder: 'static/assets'
public_folder: '../assets'

collections:
  - name: blog
    label: 博客
    folder: content/posts
    slug: '{{slug}}'
    path: '{{year}}/{{slug}}'
    create: true
    media_folder: '/static/assets'
    public_folder: '../../assets'
    nested: { depth: 10 }
    fields:
      - { name: 'title', label: '标题', widget: 'string' }
      - { name: 'date', label: '日期', widget: 'datetime' }
      - { name: 'description', label: '概述', widget: 'text', required: false }
      - { name: 'tags', label: 'Tags 标签', widget: 'list', required: false }
      - {
          name: 'featured',
          label: '精选图片',
          widget: 'image',
          required: false
        }
      - { name: 'body', label: '正文', widget: 'markdown' }
